-- Role: catalog
-- DROP ROLE IF EXISTS catalog;

CREATE ROLE catalog2 WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:dHJGMOrE9x24ChSVhlhklA==$EsPJ9a4szU4FeTTJTzUIl73Six63a9Amo/tQnIsUQ5c=:cOU8kpeZMne/tpQgVJzZdo0Cukv2GJJ0iTyRs8HA3J8=';

GRANT pg_write_all_data TO catalog2 WITH ADMIN OPTION;

CREATE SCHEMA ogr_system_tables AUTHORIZATION catalog2;